### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by Sp1l** [ScrollZ/ScrollZ#17]
I'd like to see a release so we can have a version that works with TLS and without SSLv3 and checks the server certs. Currently we have to patch the port to make this work proper, the delta is a bit too large to backport the diff between master and sz2.2.3

**Comment by justflier** [comment]
I have to look into one issue, other than that it's basically ready. Hopefully a new release will happen soon.

**Comment by justflier** [comment]
Fixed with a new release.

**Comment by Sp1l** [comment]
Thanks! Builds fine. Hope to commit an update to the FreeBSD port soon!
https://reviews.freebsd.org/D5262
