### ISSUE TITLE
Possible to compile or run in “restricted” mode?

### ISSUE THREAD

**Issue by ryanfantus** [ScrollZ/ScrollZ#22]
Hi,

Is it possible to either build or run ScrollZ in a mode that disables dcc, ctcp, etc., and removes access to anything on the underlying file system? I’d like to restrict control as much as possible from the user and dictate everything at runtime via a script. Is there already a way to do this?

Thanks.

**Comment by justflier** [comment]
There is a define DAEMON_UID, when set user matching this uid (via getuid()) is not allowed to execute certain actions such as /dcc or /exec. I am not sure if this fuits your needs, from your description I think you need to disable this for all users, not just for a specific uid. Am I correct?

**Comment by ryanfantus** [comment]
Yep, this sounds perfect, I am running scrollz as a door from a BBS so it will always be the same linux user.

Where is this defined? I see in include/irc.h that there's mention of it.

**Comment by ryanfantus** [comment]
Disregard, threw it in defs.h and am good to do. This is a nifty undocumented feature!
