### ISSUE TITLE
ReDoS vulnerability

### ISSUE THREAD

**Issue by Schievel1** [ScrollZ/ScrollZ#31]
Impact:

  A malicious irc user could nuke any other irc user that uses bitchx, ircii or
  scrollz out of irc (crash their irc client) by connecting to the same irc
  network and sending a malicious CTCP UTC message.

See also:
https://www.openwall.com/lists/oss-security/2021/03/24/2
https://bugs.gentoo.org/777987

**Comment by justflier** [comment]
I believe this was fixed  last year with commits:
- fd1e9eb9d7eae82fa923f5bcb83ea099a0fbbb4e
- 1155969d24e063b6d0b7e08b9b0c4ea8623f92ce

**Comment by Schievel1** [comment]
Ok cool, my version bump fixes this gentoo bug as well then. 

Thanks.
